[package]
name = "sum_mults"
version = "0.1.0"
authors = ["Nicholas Sterling <Nicholas.Sterling@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
