[package]
name = "sum_mults"
version = "0.1.0"
authors = ["Nicholas Sterling <Nicholas.Sterling@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
num = "0.4.3"
proptest = "1.4.0"
